.Dd December 07, 2022
.Dt HBMAP 1
.Sh NAME
.Nm hbmap
.Nd search maps from haxmaps.com
.Sh SYNOPSIS
.Nm
.Op Fl hrv
.Op Ar query
.Sh DESCRIPTION
The
.Nm
utility lets you search maps from the haxmaps.com website, it prints
the result in an easy parseable format <MAP_URL> - <MAP_NAME>.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl r
get a random map url
.It Fl v
display the program version
.El
.Sh SEE ALSO
.Xr haxmaps 1
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/hbmap/issues
